Repository Azure/azure-service-bus-dotnet, pull requests merged in 2018-06, with the labels that each got.

#485 Allow clients to report if they own or share the underlying connection string (Part 1)
  src/Microsoft.Azure.ServiceBus/ClientEntity.cs
  src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs
  src/Microsoft.Azure.ServiceBus/Core/MessageSender.cs
  src/Microsoft.Azure.ServiceBus/QueueClient.cs
  src/Microsoft.Azure.ServiceBus/SessionClient.cs
  src/Microsoft.Azure.ServiceBus/SubscriptionClient.cs
  src/Microsoft.Azure.ServiceBus/TopicClient.cs
  test/Microsoft.Azure.ServiceBus.UnitTests/API/ApiApprovals.ApproveAzureServiceBus.approved.txt
Labels: enhancement

#513 Throwing when MessageSender is unable to successfully schedule messages
  src/Microsoft.Azure.ServiceBus/Core/MessageSender.cs
Labels: bug

#512 Fixing documentation for user property types which are supported
  src/Microsoft.Azure.ServiceBus/Message.cs
  test/Microsoft.Azure.ServiceBus.UnitTests/MessageTests.cs
Labels: documentation

#511 Updated with the correct message property name for EnqueuedSequenceNumber
  src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs
Labels: bug

#481 Management Operations
  src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs
  src/Microsoft.Azure.ServiceBus/EntityNameHelper.cs
  src/Microsoft.Azure.ServiceBus/Filters/CorrelationFilter.cs
  src/Microsoft.Azure.ServiceBus/Filters/CorrelationFilterExtensions.cs
  src/Microsoft.Azure.ServiceBus/Filters/FalseFilter.cs
  src/Microsoft.Azure.ServiceBus/Filters/Filter.cs
  src/Microsoft.Azure.ServiceBus/Filters/FilterExtensions.cs
  src/Microsoft.Azure.ServiceBus/Filters/RuleAction.cs
  src/Microsoft.Azure.ServiceBus/Filters/RuleActionExtensions.cs
  src/Microsoft.Azure.ServiceBus/Filters/RuleDescription.cs
  src/Microsoft.Azure.ServiceBus/Filters/RuleDescriptionExtensions.cs
  src/Microsoft.Azure.ServiceBus/Filters/SqlFilter.cs
  src/Microsoft.Azure.ServiceBus/Filters/SqlFilterExtensions.cs
  src/Microsoft.Azure.ServiceBus/Filters/SqlRuleAction.cs
  src/Microsoft.Azure.ServiceBus/Filters/TrueFilter.cs
  src/Microsoft.Azure.ServiceBus/Filters/XmlObjectConvertor.cs
  src/Microsoft.Azure.ServiceBus/Management/AccessRights.cs
  src/Microsoft.Azure.ServiceBus/Management/AuthorizationRule.cs
  src/Microsoft.Azure.ServiceBus/Management/AuthorizationRules.cs
  src/Microsoft.Azure.ServiceBus/Management/EntityStatus.cs
  src/Microsoft.Azure.ServiceBus/Management/ManagementClient.cs
  src/Microsoft.Azure.ServiceBus/Management/ManagementClientConstants.cs
  src/Microsoft.Azure.ServiceBus/Management/MessageCountDetails.cs
  src/Microsoft.Azure.ServiceBus/Management/MessagingEntityAlreadyExistsException.cs
  src/Microsoft.Azure.ServiceBus/Management/QueueDescription.cs
  src/Microsoft.Azure.ServiceBus/Management/QueueDescriptionExtensions.cs
  src/Microsoft.Azure.ServiceBus/Management/QueueRuntimeInfo.cs
  src/Microsoft.Azure.ServiceBus/Management/QueueRuntimeInfoExtensions.cs
  src/Microsoft.Azure.ServiceBus/Management/SharedAccessAuthorizationRule.cs
  src/Microsoft.Azure.ServiceBus/Management/SubscriptionDescription.cs
  src/Microsoft.Azure.ServiceBus/Management/SubscriptionDescriptionExtensions.cs
  src/Microsoft.Azure.ServiceBus/Management/SubscriptionRuntimeInfo.cs
  src/Microsoft.Azure.ServiceBus/Management/SubscriptionRuntimeInfoExtensions.cs
  src/Microsoft.Azure.ServiceBus/Management/TopicDescription.cs
  src/Microsoft.Azure.ServiceBus/Management/TopicDescriptionExtensions.cs
  src/Microsoft.Azure.ServiceBus/Management/TopicRuntimeInfo.cs
  src/Microsoft.Azure.ServiceBus/Management/TopicRuntimeInfoExtensions.cs
  src/Microsoft.Azure.ServiceBus/MessagingEventSource.cs
  src/Microsoft.Azure.ServiceBus/Primitives/SharedAccessSignatureToken.cs
  src/Microsoft.Azure.ServiceBus/Primitives/SharedAccessSignatureTokenProvider.cs
  src/Microsoft.Azure.ServiceBus/RetryPolicy.cs
  test/Microsoft.Azure.ServiceBus.UnitTests/API/ApiApprovals.ApproveAzureServiceBus.approved.txt
  test/Microsoft.Azure.ServiceBus.UnitTests/Management/ManagementClientTests.cs
  test/Microsoft.Azure.ServiceBus.UnitTests/Microsoft.Azure.ServiceBus.UnitTests.csproj
Labels: management related

#526 Ensuring non amqp scheme URIs can also be used
  src/Microsoft.Azure.ServiceBus/Amqp/AmqpConnectionHelper.cs
  src/Microsoft.Azure.ServiceBus/Constants.cs
  test/Microsoft.Azure.ServiceBus.UnitTests/ServiceBusConnectionStringBuilderTests.cs
Labels: bug
